---
# NetApp
netapp_hostname: null
netapp_username: null
netapp_password: null

# SVM and CIFS
vserver: nfs_svm
cifs_server_name: null
cifs_domain: companieshouse.local
dns_servers: [] # e.g. ["10.0.0.10", "10.0.0.11"]

# AD
dc_admin_user_name: null
dc_admin_password: null
dc_ou: "OU=MSS Tier0,OU=MMS Tier,OU=CH-Tier-Cloud,OU=CARDIFF,OU=CH,DC=CompaniesHouse,DC=local"

# FSx Users
fsx_domain_admins: [] # e.g. ["samjones", "alexwilliams"]
